Improve error for refined class/instances conflict
tests/crash/RClass.hs:4:11:
  Error: Refined classes cannot have refined instances
    Refined class definition for: Foo
    Defined at: tests/crash/RClass.hs:4:11

    Refined instance for: Int
    Defined at: tests/crash/RClass.hs:11:16

    Refined instance for: Integer
    Defined at: tests/crash/RClass.hs:16:16